title: Heung Kit Leslie Chung # name (or website title)
logo: "/images/logo.png?raw=true" # photo (or logo)
description: > # description below
  Data Scientist with 6+ years experience across banking, health and higher education.
  <br><br>
  Currently based in Sydney, Australia. 
  <br><br>
  <a href="https://www.linkedin.com/in/hklchung/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
